# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: armazenamento_chave_valor_distribuido.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='armazenamento_chave_valor_distribuido.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n+armazenamento_chave_valor_distribuido.proto\"+\n\x0b\x43have_Valor\x12\r\n\x05\x63have\x18\x01 \x02(\x05\x12\r\n\x05valor\x18\x02 \x02(\t\"\x16\n\x05Valor\x12\r\n\x05valor\x18\x01 \x02(\t\"\x1b\n\x0b\x46lagRetorno\x12\x0c\n\x04\x66lag\x18\x01 \x02(\x05\"\x16\n\x05\x43have\x12\r\n\x05\x63have\x18\x01 \x02(\x05\"$\n\x0fStringIDServico\x12\x11\n\tidServico\x18\x01 \x02(\t\"\x0c\n\nParamVazio\"B\n\x0eRegistroChaves\x12 \n\x18\x65ndServidorArmazenamento\x18\x01 \x02(\t\x12\x0e\n\x06\x63haves\x18\x02 \x03(\x05\")\n\x14NumChavesProcessadas\x12\x11\n\tnumChaves\x18\x01 \x02(\x05\x32\xb0\x01\n\x19ServidorDeParesChaveValor\x12%\n\x07Inserir\x12\x0c.Chave_Valor\x1a\x0c.FlagRetorno\x12\x1b\n\tConsultar\x12\x06.Chave\x1a\x06.Valor\x12(\n\x06\x41tivar\x12\x10.StringIDServico\x1a\x0c.FlagRetorno\x12%\n\x08Terminar\x12\x0b.ParamVazio\x1a\x0c.FlagRetorno2\xa4\x01\n\x19ServidorCombinaServidores\x12\x33\n\tRegistrar\x12\x0f.RegistroChaves\x1a\x15.NumChavesProcessadas\x12\"\n\x06Mapear\x12\x06.Chave\x1a\x10.StringIDServico\x12.\n\x08Terminar\x12\x0b.ParamVazio\x1a\x15.NumChavesProcessadas')
)




_CHAVE_VALOR = _descriptor.Descriptor(
  name='Chave_Valor',
  full_name='Chave_Valor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='Chave_Valor.chave', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='Chave_Valor.valor', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=90,
)


_VALOR = _descriptor.Descriptor(
  name='Valor',
  full_name='Valor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valor', full_name='Valor.valor', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=114,
)


_FLAGRETORNO = _descriptor.Descriptor(
  name='FlagRetorno',
  full_name='FlagRetorno',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='FlagRetorno.flag', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=143,
)


_CHAVE = _descriptor.Descriptor(
  name='Chave',
  full_name='Chave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='Chave.chave', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=167,
)


_STRINGIDSERVICO = _descriptor.Descriptor(
  name='StringIDServico',
  full_name='StringIDServico',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idServico', full_name='StringIDServico.idServico', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=205,
)


_PARAMVAZIO = _descriptor.Descriptor(
  name='ParamVazio',
  full_name='ParamVazio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=219,
)


_REGISTROCHAVES = _descriptor.Descriptor(
  name='RegistroChaves',
  full_name='RegistroChaves',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endServidorArmazenamento', full_name='RegistroChaves.endServidorArmazenamento', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chaves', full_name='RegistroChaves.chaves', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=287,
)


_NUMCHAVESPROCESSADAS = _descriptor.Descriptor(
  name='NumChavesProcessadas',
  full_name='NumChavesProcessadas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numChaves', full_name='NumChavesProcessadas.numChaves', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=330,
)

DESCRIPTOR.message_types_by_name['Chave_Valor'] = _CHAVE_VALOR
DESCRIPTOR.message_types_by_name['Valor'] = _VALOR
DESCRIPTOR.message_types_by_name['FlagRetorno'] = _FLAGRETORNO
DESCRIPTOR.message_types_by_name['Chave'] = _CHAVE
DESCRIPTOR.message_types_by_name['StringIDServico'] = _STRINGIDSERVICO
DESCRIPTOR.message_types_by_name['ParamVazio'] = _PARAMVAZIO
DESCRIPTOR.message_types_by_name['RegistroChaves'] = _REGISTROCHAVES
DESCRIPTOR.message_types_by_name['NumChavesProcessadas'] = _NUMCHAVESPROCESSADAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chave_Valor = _reflection.GeneratedProtocolMessageType('Chave_Valor', (_message.Message,), dict(
  DESCRIPTOR = _CHAVE_VALOR,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:Chave_Valor)
  ))
_sym_db.RegisterMessage(Chave_Valor)

Valor = _reflection.GeneratedProtocolMessageType('Valor', (_message.Message,), dict(
  DESCRIPTOR = _VALOR,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:Valor)
  ))
_sym_db.RegisterMessage(Valor)

FlagRetorno = _reflection.GeneratedProtocolMessageType('FlagRetorno', (_message.Message,), dict(
  DESCRIPTOR = _FLAGRETORNO,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:FlagRetorno)
  ))
_sym_db.RegisterMessage(FlagRetorno)

Chave = _reflection.GeneratedProtocolMessageType('Chave', (_message.Message,), dict(
  DESCRIPTOR = _CHAVE,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:Chave)
  ))
_sym_db.RegisterMessage(Chave)

StringIDServico = _reflection.GeneratedProtocolMessageType('StringIDServico', (_message.Message,), dict(
  DESCRIPTOR = _STRINGIDSERVICO,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:StringIDServico)
  ))
_sym_db.RegisterMessage(StringIDServico)

ParamVazio = _reflection.GeneratedProtocolMessageType('ParamVazio', (_message.Message,), dict(
  DESCRIPTOR = _PARAMVAZIO,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:ParamVazio)
  ))
_sym_db.RegisterMessage(ParamVazio)

RegistroChaves = _reflection.GeneratedProtocolMessageType('RegistroChaves', (_message.Message,), dict(
  DESCRIPTOR = _REGISTROCHAVES,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:RegistroChaves)
  ))
_sym_db.RegisterMessage(RegistroChaves)

NumChavesProcessadas = _reflection.GeneratedProtocolMessageType('NumChavesProcessadas', (_message.Message,), dict(
  DESCRIPTOR = _NUMCHAVESPROCESSADAS,
  __module__ = 'armazenamento_chave_valor_distribuido_pb2'
  # @@protoc_insertion_point(class_scope:NumChavesProcessadas)
  ))
_sym_db.RegisterMessage(NumChavesProcessadas)



_SERVIDORDEPARESCHAVEVALOR = _descriptor.ServiceDescriptor(
  name='ServidorDeParesChaveValor',
  full_name='ServidorDeParesChaveValor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=333,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inserir',
    full_name='ServidorDeParesChaveValor.Inserir',
    index=0,
    containing_service=None,
    input_type=_CHAVE_VALOR,
    output_type=_FLAGRETORNO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Consultar',
    full_name='ServidorDeParesChaveValor.Consultar',
    index=1,
    containing_service=None,
    input_type=_CHAVE,
    output_type=_VALOR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ativar',
    full_name='ServidorDeParesChaveValor.Ativar',
    index=2,
    containing_service=None,
    input_type=_STRINGIDSERVICO,
    output_type=_FLAGRETORNO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Terminar',
    full_name='ServidorDeParesChaveValor.Terminar',
    index=3,
    containing_service=None,
    input_type=_PARAMVAZIO,
    output_type=_FLAGRETORNO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVIDORDEPARESCHAVEVALOR)

DESCRIPTOR.services_by_name['ServidorDeParesChaveValor'] = _SERVIDORDEPARESCHAVEVALOR


_SERVIDORCOMBINASERVIDORES = _descriptor.ServiceDescriptor(
  name='ServidorCombinaServidores',
  full_name='ServidorCombinaServidores',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=512,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='Registrar',
    full_name='ServidorCombinaServidores.Registrar',
    index=0,
    containing_service=None,
    input_type=_REGISTROCHAVES,
    output_type=_NUMCHAVESPROCESSADAS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Mapear',
    full_name='ServidorCombinaServidores.Mapear',
    index=1,
    containing_service=None,
    input_type=_CHAVE,
    output_type=_STRINGIDSERVICO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Terminar',
    full_name='ServidorCombinaServidores.Terminar',
    index=2,
    containing_service=None,
    input_type=_PARAMVAZIO,
    output_type=_NUMCHAVESPROCESSADAS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVIDORCOMBINASERVIDORES)

DESCRIPTOR.services_by_name['ServidorCombinaServidores'] = _SERVIDORCOMBINASERVIDORES

# @@protoc_insertion_point(module_scope)
