# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chave_valor_distribuido_pb2 as chave__valor__distribuido__pb2


class ArmazenamentoChaveValorDistribuidoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Inserir = channel.unary_unary(
        '/ArmazenamentoChaveValorDistribuido/Inserir',
        request_serializer=chave__valor__distribuido__pb2.Chave_Valor.SerializeToString,
        response_deserializer=chave__valor__distribuido__pb2.FlagRetorno.FromString,
        )
    self.Consultar = channel.unary_unary(
        '/ArmazenamentoChaveValorDistribuido/Consultar',
        request_serializer=chave__valor__distribuido__pb2.Chave.SerializeToString,
        response_deserializer=chave__valor__distribuido__pb2.Valor.FromString,
        )
    self.Ativar = channel.unary_unary(
        '/ArmazenamentoChaveValorDistribuido/Ativar',
        request_serializer=chave__valor__distribuido__pb2.StringIDServico.SerializeToString,
        response_deserializer=chave__valor__distribuido__pb2.FlagRetorno.FromString,
        )
    self.Terminar = channel.unary_unary(
        '/ArmazenamentoChaveValorDistribuido/Terminar',
        request_serializer=chave__valor__distribuido__pb2.ParamVazio.SerializeToString,
        response_deserializer=chave__valor__distribuido__pb2.FlagRetorno.FromString,
        )


class ArmazenamentoChaveValorDistribuidoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Inserir(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Consultar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ativar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Terminar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ArmazenamentoChaveValorDistribuidoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Inserir': grpc.unary_unary_rpc_method_handler(
          servicer.Inserir,
          request_deserializer=chave__valor__distribuido__pb2.Chave_Valor.FromString,
          response_serializer=chave__valor__distribuido__pb2.FlagRetorno.SerializeToString,
      ),
      'Consultar': grpc.unary_unary_rpc_method_handler(
          servicer.Consultar,
          request_deserializer=chave__valor__distribuido__pb2.Chave.FromString,
          response_serializer=chave__valor__distribuido__pb2.Valor.SerializeToString,
      ),
      'Ativar': grpc.unary_unary_rpc_method_handler(
          servicer.Ativar,
          request_deserializer=chave__valor__distribuido__pb2.StringIDServico.FromString,
          response_serializer=chave__valor__distribuido__pb2.FlagRetorno.SerializeToString,
      ),
      'Terminar': grpc.unary_unary_rpc_method_handler(
          servicer.Terminar,
          request_deserializer=chave__valor__distribuido__pb2.ParamVazio.FromString,
          response_serializer=chave__valor__distribuido__pb2.FlagRetorno.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ArmazenamentoChaveValorDistribuido', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
